export const countriesListPTBR = [
  {
    ordem: 1,
    name: 'Afeganistão',
    code: 'AF',
    code3: 'AFG',
    number: '004',
  },
  {
    ordem: 2,
    name: 'África do Sul',
    code: 'ZA',
    code3: 'ZAF',
    number: '710',
  },
  {
    ordem: 3,
    name: 'Albânia',
    code: 'AL',
    code3: 'ALB',
    number: '008',
  },
  {
    ordem: 4,
    name: 'Alemanha',
    code: 'DE',
    code3: 'DEU',
    number: '276',
  },
  {
    ordem: 5,
    name: 'Andorra',
    code: 'AD',
    code3: 'AND',
    number: '020',
  },
  {
    ordem: 6,
    name: 'Angola',
    code: 'AO',
    code3: 'AGO',
    number: '024',
  },
  {
    ordem: 7,
    name: 'Anguilla',
    code: 'AI',
    code3: 'AIA',
    number: '660',
  },
  {
    ordem: 8,
    name: 'Antártida',
    code: 'AQ',
    code3: 'ATA',
    number: '010',
  },
  {
    ordem: 9,
    name: 'Antígua e Barbuda',
    code: 'AG',
    code3: 'ATG',
    number: '028',
  },
  {
    ordem: 10,
    name: 'Antilhas Holandesas',
    code: 'AN',
    code3: 'ANT',
    number: '530',
  },
  {
    ordem: 11,
    name: 'Arábia Saudita',
    code: 'SA',
    code3: 'SAU',
    number: '682',
  },
  {
    ordem: 12,
    name: 'Argélia',
    code: 'DZ',
    code3: 'DZA',
    number: '012',
  },
  {
    ordem: 13,
    name: 'Argentina',
    code: 'AR',
    code3: 'ARG',
    number: '032',
  },
  {
    ordem: 14,
    name: 'Armênia',
    code: 'AM',
    code3: 'ARM',
    number: '51',
  },
  {
    ordem: 15,
    name: 'Aruba',
    code: 'AW',
    code3: 'ABW',
    number: '533',
  },
  {
    ordem: 16,
    name: 'Austrália',
    code: 'AU',
    code3: 'AUS',
    number: '036',
  },
  {
    ordem: 17,
    name: 'Áustria',
    code: 'AT',
    code3: 'AUT',
    number: '040',
  },
  {
    ordem: 18,
    name: 'Azerbaijão',
    code: 'AZ  ',
    code3: 'AZE',
    number: '31',
  },
  {
    ordem: 19,
    name: 'Bahamas',
    code: 'BS',
    code3: 'BHS',
    number: '044',
  },
  {
    ordem: 20,
    name: 'Bahrein',
    code: 'BH',
    code3: 'BHR',
    number: '048',
  },
  {
    ordem: 21,
    name: 'Bangladesh',
    code: 'BD',
    code3: 'BGD',
    number: '050',
  },
  {
    ordem: 22,
    name: 'Barbados',
    code: 'BB',
    code3: 'BRB',
    number: '052',
  },
  {
    ordem: 23,
    name: 'Belarus',
    code: 'BY',
    code3: 'BLR',
    number: '112',
  },
  {
    ordem: 24,
    name: 'Bélgica',
    code: 'BE',
    code3: 'BEL',
    number: '056',
  },
  {
    ordem: 25,
    name: 'Belize',
    code: 'BZ',
    code3: 'BLZ',
    number: '084',
  },
  {
    ordem: 26,
    name: 'Benin',
    code: 'BJ',
    code3: 'BEN',
    number: '204',
  },
  {
    ordem: 27,
    name: 'Bermudas',
    code: 'BM',
    code3: 'BMU',
    number: '060',
  },
  {
    ordem: 28,
    name: 'Bolívia',
    code: 'BO',
    code3: 'BOL',
    number: '068',
  },
  {
    ordem: 29,
    name: 'Bósnia-Herzegóvina',
    code: 'BA',
    code3: 'BIH',
    number: '070',
  },
  {
    ordem: 30,
    name: 'Botsuana',
    code: 'BW',
    code3: 'BWA',
    number: '072',
  },
  {
    ordem: 31,
    name: 'Brasil',
    code: 'BR',
    code3: 'BRA',
    number: '076',
  },
  {
    ordem: 32,
    name: 'Brunei',
    code: 'BN',
    code3: 'BRN',
    number: '096',
  },
  {
    ordem: 33,
    name: 'Bulgária',
    code: 'BG',
    code3: 'BGR',
    number: '100',
  },
  {
    ordem: 34,
    name: 'Burkina Fasso',
    code: 'BF',
    code3: 'BFA',
    number: '854',
  },
  {
    ordem: 35,
    name: 'Burundi',
    code: 'BI',
    code3: 'BDI',
    number: '108',
  },
  {
    ordem: 36,
    name: 'Butão',
    code: 'BT',
    code3: 'BTN',
    number: '064',
  },
  {
    ordem: 37,
    name: 'Cabo Verde',
    code: 'CV',
    code3: 'CPV',
    number: '132',
  },
  {
    ordem: 38,
    name: 'Camarões',
    code: 'CM',
    code3: 'CMR',
    number: '120',
  },
  {
    ordem: 39,
    name: 'Camboja',
    code: 'KH',
    code3: 'KHM',
    number: '116',
  },
  {
    ordem: 40,
    name: 'Canadá',
    code: 'CA',
    code3: 'CAN',
    number: '124',
  },
  {
    ordem: 41,
    name: 'Cazaquistão',
    code: 'KZ',
    code3: 'KAZ',
    number: '398',
  },
  {
    ordem: 42,
    name: 'Chade',
    code: 'TD',
    code3: 'TCD',
    number: '148',
  },
  {
    ordem: 43,
    name: 'Chile',
    code: 'CL',
    code3: 'CHL',
    number: '152',
  },
  {
    ordem: 44,
    name: 'China',
    code: 'CN',
    code3: 'CHN',
    number: '156',
  },
  {
    ordem: 45,
    name: 'Chipre',
    code: 'CY',
    code3: 'CYP',
    number: '196',
  },
  {
    ordem: 46,
    name: 'Cingapura',
    code: 'SG',
    code3: 'SGP',
    number: '702',
  },
  {
    ordem: 47,
    name: 'Colômbia',
    code: 'CO',
    code3: 'COL',
    number: '170',
  },
  {
    ordem: 48,
    name: 'Congo',
    code: 'CG',
    code3: 'COG',
    number: '178',
  },
  {
    ordem: 49,
    name: 'Coréia do Norte',
    code: 'KP',
    code3: 'PRK',
    number: '408',
  },
  {
    ordem: 50,
    name: 'Coréia do Sul',
    code: 'KR',
    code3: 'KOR',
    number: '410',
  },
  {
    ordem: 51,
    name: 'Costa do Marfim',
    code: 'CI',
    code3: 'CIV',
    number: '384',
  },
  {
    ordem: 52,
    name: 'Costa Rica',
    code: 'CR',
    code3: 'CRI',
    number: '188',
  },
  {
    ordem: 53,
    name: 'Croácia (Hrvatska)',
    code: 'HR',
    code3: 'HRV',
    number: '191',
  },
  {
    ordem: 54,
    name: 'Cuba',
    code: 'CU',
    code3: 'CUB',
    number: '192',
  },
  {
    ordem: 55,
    name: 'Dinamarca',
    code: 'DK',
    code3: 'DNK',
    number: '208',
  },
  {
    ordem: 56,
    name: 'Djibuti',
    code: 'DJ',
    code3: 'DJI',
    number: '262',
  },
  {
    ordem: 57,
    name: 'Dominica',
    code: 'DM',
    code3: 'DMA',
    number: '212',
  },
  {
    ordem: 58,
    name: 'Egito',
    code: 'EG',
    code3: 'EGY',
    number: '818',
  },
  {
    ordem: 59,
    name: 'El Salvador',
    code: 'SV',
    code3: 'SLV',
    number: '222',
  },
  {
    ordem: 60,
    name: 'Emirados Árabes Unidos',
    code: 'AE',
    code3: 'ARE',
    number: '784',
  },
  {
    ordem: 61,
    name: 'Equador',
    code: 'EC',
    code3: 'ECU',
    number: '218',
  },
  {
    ordem: 62,
    name: 'Eritréia',
    code: 'ER',
    code3: 'ERI',
    number: '232',
  },
  {
    ordem: 63,
    name: 'Eslováquia',
    code: 'SK',
    code3: 'SVK',
    number: '703',
  },
  {
    ordem: 64,
    name: 'Eslovênia',
    code: 'SI',
    code3: 'SVN',
    number: '705',
  },
  {
    ordem: 65,
    name: 'Espanha',
    code: 'ES',
    code3: 'ESP',
    number: '724',
  },
  {
    ordem: 66,
    name: 'Estados Unidos',
    code: 'US',
    code3: 'USA',
    number: '840',
  },
  {
    ordem: 67,
    name: 'Estônia',
    code: 'EE',
    code3: 'EST',
    number: '233',
  },
  {
    ordem: 68,
    name: 'Etiópia',
    code: 'ET',
    code3: 'ETH',
    number: '231',
  },
  {
    ordem: 69,
    name: 'Fiji',
    code: 'FJ',
    code3: 'FJI',
    number: '242',
  },
  {
    ordem: 70,
    name: 'Filipinas',
    code: 'PH',
    code3: 'PHL',
    number: '608',
  },
  {
    ordem: 71,
    name: 'Finlândia',
    code: 'FI',
    code3: 'FIN',
    number: '246',
  },
  {
    ordem: 72,
    name: 'França',
    code: 'FR',
    code3: 'FRA',
    number: '250',
  },
  {
    ordem: 73,
    name: 'Gabão',
    code: 'GA',
    code3: 'GAB',
    number: '266',
  },
  {
    ordem: 74,
    name: 'Gâmbia',
    code: 'GM',
    code3: 'GMB',
    number: '270',
  },
  {
    ordem: 75,
    name: 'Gana',
    code: 'GH',
    code3: 'GHA',
    number: '288',
  },
  {
    ordem: 76,
    name: 'Geórgia',
    code: 'GE',
    code3: 'GEO',
    number: '268',
  },
  {
    ordem: 77,
    name: 'Gibraltar',
    code: 'GI',
    code3: 'GIB',
    number: '292',
  },
  {
    ordem: 78,
    name: 'Grã-Bretanha (Reino Unido, UK)',
    code: 'GB',
    code3: 'GBR',
    number: '826',
  },
  {
    ordem: 79,
    name: 'Granada',
    code: 'GD',
    code3: 'GRD',
    number: '308',
  },
  {
    ordem: 80,
    name: 'Grécia',
    code: 'GR',
    code3: 'GRC',
    number: '300',
  },
  {
    ordem: 81,
    name: 'Groelândia',
    code: 'GL',
    code3: 'GRL',
    number: '304',
  },
  {
    ordem: 82,
    name: 'Guadalupe',
    code: 'GP',
    code3: 'GLP',
    number: '312',
  },
  {
    ordem: 83,
    name: 'Guam (Território dos Estados Unidos)',
    code: 'GU',
    code3: 'GUM',
    number: '316',
  },
  {
    ordem: 84,
    name: 'Guatemala',
    code: 'GT',
    code3: 'GTM',
    number: '320',
  },
  {
    ordem: 85,
    name: 'Guernsey',
    code: 'G',
    code3: 'GGY',
    number: '832',
  },
  {
    ordem: 86,
    name: 'Guiana',
    code: 'GY',
    code3: 'GUY',
    number: '328',
  },
  {
    ordem: 87,
    name: 'Guiana Francesa',
    code: 'GF',
    code3: 'GUF',
    number: '254',
  },
  {
    ordem: 88,
    name: 'Guiné',
    code: 'GN',
    code3: 'GIN',
    number: '324',
  },
  {
    ordem: 89,
    name: 'Guiné Equatorial',
    code: 'GQ',
    code3: 'GNQ',
    number: '226',
  },
  {
    ordem: 90,
    name: 'Guiné-Bissau',
    code: 'GW',
    code3: 'GNB',
    number: '624',
  },
  {
    ordem: 91,
    name: 'Haiti',
    code: 'HT',
    code3: 'HTI',
    number: '332',
  },
  {
    ordem: 92,
    name: 'Holanda',
    code: 'NL',
    code3: 'NLD',
    number: '528',
  },
  {
    ordem: 93,
    name: 'Honduras',
    code: 'HN',
    code3: 'HND',
    number: '340',
  },
  {
    ordem: 94,
    name: 'Hong Kong',
    code: 'HK',
    code3: 'HKG',
    number: '344',
  },
  {
    ordem: 95,
    name: 'Hungria',
    code: 'HU',
    code3: 'HUN',
    number: '348',
  },
  {
    ordem: 96,
    name: 'Iêmen',
    code: 'YE',
    code3: 'YEM',
    number: '887',
  },
  {
    ordem: 97,
    name: 'Ilha Bouvet (Território da Noruega)',
    code: 'BV',
    code3: 'BVT',
    number: '074',
  },
  {
    ordem: 98,
    name: 'Ilha do Homem',
    code: 'IM',
    code3: 'IMN',
    number: '833',
  },
  {
    ordem: 99,
    name: 'Ilha Natal',
    code: 'CX',
    code3: 'CXR',
    number: '162',
  },
  {
    ordem: 100,
    name: 'Ilha Pitcairn',
    code: 'PN',
    code3: 'PCN',
    number: '612',
  },
  {
    ordem: 101,
    name: 'Ilha Reunião',
    code: 'RE',
    code3: 'REU',
    number: '638',
  },
  {
    ordem: 102,
    name: 'Ilhas Aland',
    code: 'AX',
    code3: 'ALA',
    number: '248',
  },
  {
    ordem: 103,
    name: 'Ilhas Cayman',
    code: 'KY',
    code3: 'CYM',
    number: '136',
  },
  {
    ordem: 104,
    name: 'Ilhas Cocos',
    code: 'CC',
    code3: 'CCK',
    number: '166',
  },
  {
    ordem: 105,
    name: 'Ilhas Comores',
    code: 'KM',
    code3: 'COM',
    number: '174',
  },
  {
    ordem: 106,
    name: 'Ilhas Cook',
    code: 'CK',
    code3: 'COK',
    number: '184',
  },
  {
    ordem: 107,
    name: 'Ilhas Faroes',
    code: 'FO',
    code3: 'FRO',
    number: '234',
  },
  {
    ordem: 108,
    name: 'Ilhas Falkland (Malvinas)',
    code: 'FK',
    code3: 'FLK',
    number: '238',
  },
  {
    ordem: 109,
    name: 'Ilhas Geórgia do Sul e Sandwich do Sul',
    code: 'GS',
    code3: 'SGS',
    number: '239',
  },
  {
    ordem: 110,
    name: 'Ilhas Heard e McDonald (Território da Austrália)',
    code: 'HM',
    code3: 'HMD',
    number: '334',
  },
  {
    ordem: 111,
    name: 'Ilhas Marianas do Norte',
    code: 'MP',
    code3: 'MNP',
    number: '580',
  },
  {
    ordem: 112,
    name: 'Ilhas Marshall',
    code: 'MH',
    code3: 'MHL',
    number: '584',
  },
  {
    ordem: 113,
    name: 'Ilhas Menores dos Estados Unidos',
    code: 'UM',
    code3: 'UMI',
    number: '581',
  },
  {
    ordem: 114,
    name: 'Ilhas Norfolk',
    code: 'NF',
    code3: 'NFK',
    number: '574',
  },
  {
    ordem: 115,
    name: 'Ilhas Seychelles',
    code: 'SC',
    code3: 'SYC',
    number: '690',
  },
  {
    ordem: 116,
    name: 'Ilhas Solomão',
    code: 'SB',
    code3: 'SLB',
    number: '090',
  },
  {
    ordem: 117,
    name: 'Ilhas Svalbard e Jan Mayen',
    code: 'SJ',
    code3: 'SJM',
    number: '744',
  },
  {
    ordem: 118,
    name: 'Ilhas Tokelau',
    code: 'TK',
    code3: 'TKL',
    number: '772',
  },
  {
    ordem: 119,
    name: 'Ilhas Turks e Caicos',
    code: 'TC',
    code3: 'TCA',
    number: '796',
  },
  {
    ordem: 120,
    name: 'Ilhas Virgens (Estados Unidos)',
    code: 'VI',
    code3: 'VIR',
    number: '850',
  },
  {
    ordem: 121,
    name: 'Ilhas Virgens (Inglaterra)',
    code: 'VG',
    code3: 'VGB',
    number: '092',
  },
  {
    ordem: 122,
    name: 'Ilhas Wallis e Futuna',
    code: 'WF',
    code3: 'WLF',
    number: '876',
  },
  {
    ordem: 123,
    name: 'índia',
    code: 'IN',
    code3: 'IND',
    number: '356',
  },
  {
    ordem: 124,
    name: 'Indonésia',
    code: 'ID',
    code3: 'IDN',
    number: '360',
  },
  {
    ordem: 125,
    name: 'Irã',
    code: 'IR',
    code3: 'IRN',
    number: '364',
  },
  {
    ordem: 126,
    name: 'Iraque',
    code: 'IQ',
    code3: 'IRQ',
    number: '368',
  },
  {
    ordem: 127,
    name: 'Irlanda',
    code: 'IE',
    code3: 'IRL',
    number: '372',
  },
  {
    ordem: 128,
    name: 'Islândia',
    code: 'IS',
    code3: 'ISL',
    number: '352',
  },
  {
    ordem: 129,
    name: 'Israel',
    code: 'IL',
    code3: 'ISR',
    number: '376',
  },
  {
    ordem: 130,
    name: 'Itália',
    code: 'IT',
    code3: 'ITA',
    number: '380',
  },
  {
    ordem: 131,
    name: 'Jamaica',
    code: 'JM',
    code3: 'JAM',
    number: '388',
  },
  {
    ordem: 132,
    name: 'Japão',
    code: 'JP',
    code3: 'JPN',
    number: '392',
  },
  {
    ordem: 133,
    name: 'Jersey',
    code: 'JE',
    code3: 'JEY',
    number: '832',
  },
  {
    ordem: 134,
    name: 'Jordânia',
    code: 'JO',
    code3: 'JOR',
    number: '400',
  },
  {
    ordem: 135,
    name: 'Kênia',
    code: 'KE',
    code3: 'KEN',
    number: '404',
  },
  {
    ordem: 136,
    name: 'Kiribati',
    code: 'KI',
    code3: 'KIR',
    number: '296',
  },
  {
    ordem: 137,
    name: 'Kuait',
    code: 'KW',
    code3: 'KWT',
    number: '414',
  },
  {
    ordem: 138,
    name: 'Laos',
    code: 'LA',
    code3: 'LAO',
    number: '418',
  },
  {
    ordem: 139,
    name: 'Látvia',
    code: 'LV',
    code3: 'LVA',
    number: '428',
  },
  {
    ordem: 140,
    name: 'Lesoto',
    code: 'LS',
    code3: 'LSO',
    number: '426',
  },
  {
    ordem: 141,
    name: 'Líbano',
    code: 'LB',
    code3: 'LBN',
    number: '422',
  },
  {
    ordem: 142,
    name: 'Libéria',
    code: 'LR',
    code3: 'LBR',
    number: '430',
  },
  {
    ordem: 143,
    name: 'Líbia',
    code: 'LY',
    code3: 'LBY',
    number: '434',
  },
  {
    ordem: 144,
    name: 'Liechtenstein',
    code: 'LI',
    code3: 'LIE',
    number: '438',
  },
  {
    ordem: 145,
    name: 'Lituânia',
    code: 'LT',
    code3: 'LTU',
    number: '440',
  },
  {
    ordem: 146,
    name: 'Luxemburgo',
    code: 'LU',
    code3: 'LUX',
    number: '442',
  },
  {
    ordem: 147,
    name: 'Macau',
    code: 'MO',
    code3: 'MAC',
    number: '446',
  },
  {
    ordem: 148,
    name: 'Macedônia (República Yugoslava)',
    code: 'MK',
    code3: 'MKD',
    number: '807',
  },
  {
    ordem: 149,
    name: 'Madagascar',
    code: 'MG',
    code3: 'MDG',
    number: '450',
  },
  {
    ordem: 150,
    name: 'Malásia',
    code: 'MY',
    code3: 'MYS',
    number: '458',
  },
  {
    ordem: 151,
    name: 'Malaui',
    code: 'MW',
    code3: 'MWI',
    number: '454',
  },
  {
    ordem: 152,
    name: 'Maldivas',
    code: 'MV',
    code3: 'MDV',
    number: '462',
  },
  {
    ordem: 153,
    name: 'Mali',
    code: 'ML',
    code3: 'MLI',
    number: '466',
  },
  {
    ordem: 154,
    name: 'Malta',
    code: 'MT',
    code3: 'MLT',
    number: '470',
  },
  {
    ordem: 155,
    name: 'Marrocos',
    code: 'MA',
    code3: 'MAR',
    number: '504',
  },
  {
    ordem: 156,
    name: 'Martinica',
    code: 'MQ',
    code3: 'MTQ',
    number: '474',
  },
  {
    ordem: 157,
    name: 'Maurício',
    code: 'MU',
    code3: 'MUS',
    number: '480',
  },
  {
    ordem: 158,
    name: 'Mauritânia',
    code: 'MR',
    code3: 'MRT',
    number: '478',
  },
  {
    ordem: 159,
    name: 'Mayotte',
    code: 'YT',
    code3: 'MYT',
    number: '175',
  },
  {
    ordem: 160,
    name: 'México',
    code: 'MX',
    code3: 'MEX',
    number: '484',
  },
  {
    ordem: 161,
    name: 'Micronésia',
    code: 'FM',
    code3: 'FSM',
    number: '583',
  },
  {
    ordem: 162,
    name: 'Moçambique',
    code: 'MZ',
    code3: 'MOZ',
    number: '508',
  },
  {
    ordem: 163,
    name: 'Moldova',
    code: 'MD',
    code3: 'MDA',
    number: '498',
  },
  {
    ordem: 164,
    name: 'Mônaco',
    code: 'MC',
    code3: 'MCO',
    number: '492',
  },
  {
    ordem: 165,
    name: 'Mongólia',
    code: 'MN',
    code3: 'MNG',
    number: '496',
  },
  {
    ordem: 166,
    name: 'Montenegro',
    code: 'ME',
    code3: 'MNE',
    number: '499',
  },
  {
    ordem: 167,
    name: 'Montserrat',
    code: 'MS',
    code3: 'MSR',
    number: '500',
  },
  {
    ordem: 168,
    name: 'Myanma',
    code: 'MM',
    code3: 'MMR',
    number: '104',
  },
  {
    ordem: 169,
    name: 'Namíbia',
    code: 'NA',
    code3: 'NAM',
    number: '516',
  },
  {
    ordem: 170,
    name: 'Nauru',
    code: 'NR',
    code3: 'NRU',
    number: '520',
  },
  {
    ordem: 171,
    name: 'Nepal',
    code: 'NP',
    code3: 'NPL',
    number: '524',
  },
  {
    ordem: 172,
    name: 'Nicarágua',
    code: 'NI',
    code3: 'NIC',
    number: '558',
  },
  {
    ordem: 173,
    name: 'Níger',
    code: 'NE',
    code3: 'NER',
    number: '562',
  },
  {
    ordem: 174,
    name: 'Nigéria',
    code: 'NG',
    code3: 'NGA',
    number: '566',
  },
  {
    ordem: 175,
    name: 'Niue',
    code: 'NU',
    code3: 'NIU',
    number: '570',
  },
  {
    ordem: 176,
    name: 'Noruega',
    code: 'NO',
    code3: 'NOR',
    number: '578',
  },
  {
    ordem: 177,
    name: 'Nova Caledônia',
    code: 'NC',
    code3: 'NCL',
    number: '540',
  },
  {
    ordem: 178,
    name: 'Nova Zelândia',
    code: 'NZ',
    code3: 'NZL',
    number: '554',
  },
  {
    ordem: 179,
    name: 'Omã',
    code: 'OM',
    code3: 'OMN',
    number: '512',
  },
  {
    ordem: 180,
    name: 'Palau',
    code: 'PW',
    code3: 'PLW',
    number: '585',
  },
  {
    ordem: 181,
    name: 'Panamá',
    code: 'PA',
    code3: 'PAN',
    number: '591',
  },
  {
    ordem: 182,
    name: 'Papua-Nova Guiné',
    code: 'PG',
    code3: 'PNG',
    number: '598',
  },
  {
    ordem: 183,
    name: 'Paquistão',
    code: 'PK',
    code3: 'PAK',
    number: '586',
  },
  {
    ordem: 184,
    name: 'Paraguai',
    code: 'PY',
    code3: 'PRY',
    number: '600',
  },
  {
    ordem: 185,
    name: 'Peru',
    code: 'PE',
    code3: 'PER',
    number: '604',
  },
  {
    ordem: 186,
    name: 'Polinésia Francesa',
    code: 'PF',
    code3: 'PYF',
    number: '258',
  },
  {
    ordem: 187,
    name: 'Polônia',
    code: 'PL',
    code3: 'POL',
    number: '616',
  },
  {
    ordem: 188,
    name: 'Porto Rico',
    code: 'PR',
    code3: 'PRI',
    number: '630',
  },
  {
    ordem: 189,
    name: 'Portugal',
    code: 'PT',
    code3: 'PRT',
    number: '620',
  },
  {
    ordem: 190,
    name: 'Qatar',
    code: 'QA',
    code3: 'QAT',
    number: '634',
  },
  {
    ordem: 191,
    name: 'Quirguistão',
    code: 'KG',
    code3: 'KGZ',
    number: '417',
  },
  {
    ordem: 192,
    name: 'República Centro-Africana',
    code: 'CF',
    code3: 'CAF',
    number: '140',
  },
  {
    ordem: 193,
    name: 'República Democrática do Congo',
    code: 'CD',
    code3: 'COD',
    number: '180',
  },
  {
    ordem: 194,
    name: 'República Dominicana',
    code: 'DO',
    code3: 'DOM',
    number: '214',
  },
  {
    ordem: 195,
    name: 'República Tcheca',
    code: 'CZ',
    code3: 'CZE',
    number: '203',
  },
  {
    ordem: 196,
    name: 'Romênia',
    code: 'RO',
    code3: 'ROM',
    number: '642',
  },
  {
    ordem: 197,
    name: 'Ruanda',
    code: 'RW',
    code3: 'RWA',
    number: '646',
  },
  {
    ordem: 198,
    name: 'Rússia',
    code: 'RU',
    code3: 'RUS',
    number: '643',
  },
  {
    ordem: 199,
    name: 'Saara Ocidental',
    code: 'EH',
    code3: 'ESH',
    number: '732',
  },
  {
    ordem: 200,
    name: 'Saint Vincente e Granadinas',
    code: 'VC',
    code3: 'VCT',
    number: '670',
  },
  {
    ordem: 201,
    name: 'Samoa Americana',
    code: 'AS',
    code3: 'ASM',
    number: '016',
  },
  {
    ordem: 202,
    name: 'Samoa Ocidental',
    code: 'WS',
    code3: 'WSM',
    number: '882',
  },
  {
    ordem: 203,
    name: 'San Marino',
    code: 'SM',
    code3: 'SMR',
    number: '674',
  },
  {
    ordem: 204,
    name: 'Santa Helena',
    code: 'SH',
    code3: 'SHN',
    number: '654',
  },
  {
    ordem: 205,
    name: 'Santa Lúcia',
    code: 'LC',
    code3: 'LCA',
    number: '662',
  },
  {
    ordem: 206,
    name: 'São Bartolomeu',
    code: 'BL',
    code3: 'BLM',
    number: '652',
  },
  {
    ordem: 207,
    name: 'São Cristóvão e Névis',
    code: 'KN',
    code3: 'KNA',
    number: '659',
  },
  {
    ordem: 208,
    name: 'São Martim',
    code: 'MF',
    code3: 'MAF',
    number: '663',
  },
  {
    ordem: 209,
    name: 'São Tomé e Príncipe',
    code: 'ST',
    code3: 'STP',
    number: '678',
  },
  {
    ordem: 210,
    name: 'Senegal',
    code: 'SN',
    code3: 'SEN',
    number: '686',
  },
  {
    ordem: 211,
    name: 'Serra Leoa',
    code: 'SL',
    code3: 'SLE',
    number: '694',
  },
  {
    ordem: 212,
    name: 'Sérvia',
    code: 'RS',
    code3: 'SRB',
    number: '688',
  },
  {
    ordem: 213,
    name: 'Síria',
    code: 'SY',
    code3: 'SYR',
    number: '760',
  },
  {
    ordem: 214,
    name: 'Somália',
    code: 'SO',
    code3: 'SOM',
    number: '706',
  },
  {
    ordem: 215,
    name: 'Sri Lanka',
    code: 'LK',
    code3: 'LKA',
    number: '144',
  },
  {
    ordem: 216,
    name: 'St. Pierre and Miquelon',
    code: 'PM',
    code3: 'SPM',
    number: '666',
  },
  {
    ordem: 217,
    name: 'Suazilândia',
    code: 'SZ',
    code3: 'SWZ',
    number: '748',
  },
  {
    ordem: 218,
    name: 'Sudão',
    code: 'SD',
    code3: 'SDN',
    number: '736',
  },
  {
    ordem: 219,
    name: 'Suécia',
    code: 'SE',
    code3: 'SWE',
    number: '752',
  },
  {
    ordem: 220,
    name: 'Suíça',
    code: 'CH',
    code3: 'CHE',
    number: '756',
  },
  {
    ordem: 221,
    name: 'Suriname',
    code: 'SR',
    code3: 'SUR',
    number: '740',
  },
  {
    ordem: 222,
    name: 'Tadjiquistão',
    code: 'TJ',
    code3: 'TJK',
    number: '762',
  },
  {
    ordem: 223,
    name: 'Tailândia',
    code: 'TH',
    code3: 'THA',
    number: '764',
  },
  {
    ordem: 224,
    name: 'Taiwan',
    code: 'TW',
    code3: 'TWN',
    number: '158',
  },
  {
    ordem: 225,
    name: 'Tanzânia',
    code: 'TZ',
    code3: 'TZA',
    number: '834',
  },
  {
    ordem: 226,
    name: 'Território Britânico do Oceano índico',
    code: 'IO',
    code3: 'IOT',
    number: '086',
  },
  {
    ordem: 227,
    name: 'Territórios do Sul da França',
    code: 'TF',
    code3: 'ATF',
    number: '260',
  },
  {
    ordem: 228,
    name: 'Territórios Palestinos Ocupados',
    code: 'PS',
    code3: 'PSE',
    number: '275',
  },
  {
    ordem: 229,
    name: 'Timor Leste',
    code: 'TP',
    code3: 'TMP',
    number: '626',
  },
  {
    ordem: 230,
    name: 'Togo',
    code: 'TG',
    code3: 'TGO',
    number: '768',
  },
  {
    ordem: 231,
    name: 'Tonga',
    code: 'TO',
    code3: 'TON',
    number: '776',
  },
  {
    ordem: 232,
    name: 'Trinidad and Tobago',
    code: 'TT',
    code3: 'TTO',
    number: '780',
  },
  {
    ordem: 233,
    name: 'Tunísia',
    code: 'TN',
    code3: 'TUN',
    number: '788',
  },
  {
    ordem: 234,
    name: 'Turcomenistão',
    code: 'TM',
    code3: 'TKM',
    number: '795',
  },
  {
    ordem: 235,
    name: 'Turquia',
    code: 'TR',
    code3: 'TUR',
    number: '792',
  },
  {
    ordem: 236,
    name: 'Tuvalu',
    code: 'TV',
    code3: 'TUV',
    number: '798',
  },
  {
    ordem: 237,
    name: 'Ucrânia',
    code: 'UA',
    code3: 'UKR',
    number: '804',
  },
  {
    ordem: 238,
    name: 'Uganda',
    code: 'UG',
    code3: 'UGA',
    number: '800',
  },
  {
    ordem: 239,
    name: 'Uruguai',
    code: 'UY',
    code3: 'URY',
    number: '858',
  },
  {
    ordem: 240,
    name: 'Uzbequistão',
    code: 'UZ',
    code3: 'UZB',
    number: '860',
  },
  {
    ordem: 241,
    name: 'Vanuatu',
    code: 'VU',
    code3: 'VUT',
    number: '548',
  },
  {
    ordem: 242,
    name: 'Vaticano',
    code: 'VA',
    code3: 'VAT',
    number: '336',
  },
  {
    ordem: 243,
    name: 'Venezuela',
    code: 'VE',
    code3: 'VEN',
    number: '862',
  },
  {
    ordem: 244,
    name: 'Vietnã',
    code: 'VN',
    code3: 'VNM',
    number: '704',
  },
  {
    ordem: 245,
    name: 'Zâmbia',
    code: 'ZM',
    code3: 'ZMB',
    number: '894',
  },
  {
    ordem: 246,
    name: 'Zimbábue',
    code: 'ZW',
    code3: 'ZWE',
    number: '716',
  },
];
